kind=defined
names=assert_send
visibility=public

--- assert_send(send_array, message="")    -> ()

send_array[0].__send__(send_array[1], *send_array[2..-1])
が真ならパスします。

@raise Test::Unit::AssertionFailedError assert が失敗した時に発生します。

